#ifndef OBJECT_DETECTOR_H
#define OBJECT_DETECTOR_H

#include "Common.h"
#include "Detection.h"
#include "ParametersMap.h"
#include "SupportVectorMachine.h"

using namespace cv;

// Class responsible for performing Non-Maxima Suppression on the response
// pyramid generated by SupportVectorMachine
class ObjectDetector:HOGDescriptor
{
public:
    ObjectDetector();
    ~ObjectDetector();

    void getDetections(Mat img, vector<Rect>& found);
    void detectLinearKernel(const Mat& img, vector<Point>& hits, vector<double>& weights, double hitThreshold,
    											Size winStride, Size padding, const vector<Point>& locations);
    void detectRBFKernel(const Mat& img, vector<Point>& hits, vector<double>& weights, double hitThreshold,
    											Size winStride, Size padding, const vector<Point>& locations);
    void setDetector(vector<float> svmDetector);

private:
	// HOGDescriptor _hog;
	// vector<float> _svmDetector;

};

#endif // OBJECT_DETECTOR_H