#ifndef OBJECT_DETECTOR_H
#define OBJECT_DETECTOR_H

#include "Common.h"
#include "Detection.h"
#include "ParametersMap.h"
#include "SupportVectorMachine.h"

using namespace cv;

// Class responsible for performing Non-Maxima Suppression on the response
// pyramid generated by SupportVectorMachine
class ObjectDetector
{
public:
    ObjectDetector(vector<float> svmDetector);
    ~ObjectDetector();

    void getDetections(Mat img, vector<Rect>& found);

private:
	HOGDescriptor _hog;
	vector<float> _svmDetector;

};

#endif // OBJECT_DETECTOR_H