#ifndef OBJECT_DETECTOR_H
#define OBJECT_DETECTOR_H

#include "Common.h"
#include "Detection.h"
#include "ParametersMap.h"
#include "SupportVectorMachine.h"

using namespace cv;

// Class responsible for performing Non-Maxima Suppression on the response
// pyramid generated by SupportVectorMachine
class ObjectDetector
{
public:
    ObjectDetector(FeatureExtractor* featExtractor, SupportVectorMachine svm);
    ~ObjectDetector();

    void getDetections(Mat img);//, FeatureExtractor* featExtractor, SupportVectorMachine svm);//, vector<Detection>& dets);

private:

	FeatureExtractor* _featExtractor;
	SupportVectorMachine _svm;

};

#endif // OBJECT_DETECTOR_H