PLOT1 = '/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL_SMALL/PERSON/MODELS/LINEAR/prcurve_C_0_1.pr';
PLOT2 = '/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL_SMALL/PERSON/MODELS/LINEAR/prcurve_C_0_01.pr';
PLOT3 = '/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL_SMALL/PERSON/MODELS/LINEAR/prcurve_C_10.pr';

PLOT4 = '/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL_SMALL/PERSON/MODELS/RBF/prcurve_C_0_1_G_0_0001.pr';
PLOT5 = '/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL_SMALL/PERSON/MODELS/RBF/prcurve_C_0_1_G_0_1.pr';
PLOT6 = '/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL_SMALL/PERSON/MODELS/RBF/prcurve_C_0_1_G_1.pr';

plot_pr('PR PERSON CLASS',PLOT4,'G=0.0001',PLOT5,'G=0.1', PLOT6,'G=1');