PLOT1 = '/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL_SMALL/PERSON/MODELS/LINEAR/prcurve_C_100.pr';
PLOT2 = '/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL_SMALL/PERSON/MODELS/LINEAR/prcurve_C_0_01.pr';
PLOT3 = '/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL_SMALL/PERSON/MODELS/LINEAR/prcurve_C_0_0001.pr';

PLOT4 = '/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL_SMALL/PERSON/MODELS/RBF/prcurve_C_0_1_G_0_0001.pr';
PLOT5 = '/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL_SMALL/PERSON/MODELS/RBF/prcurve_C_0_1_G_0_1.pr';
PLOT6 = '/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL_SMALL/PERSON/MODELS/RBF/prcurve_C_0_1_G_1.pr';

PLOT5 = 'prcurve_C_0_00001.pr';
PLOT6 = 'prcurve_C_0_01.pr';
PLOT7 = 'prcurve_C_100.pr';
PLOT8 = '/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL_SMALL/PERSON/MODELS/LINEAR/TEST/prcurve_C_0_01.pr';
PLOT9 = '/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL_SMALL/PERSON/MODELS/RBF/TEST/prcurve_G_0_01.pr';

%plot_pr('PR PERSON CLASS - LINEAR KERNEL',PLOT5,'C=0.00001',PLOT6,'C=0.01', PLOT7,'C=100');

plot_pr('PR PERSON CLASS TEST',PLOT8,'LINEAR KERNEL', PLOT9,'RBF KERNEL');