#! /bin/bash
clear

echo "This script automates the training and cross validation for the Object Detection Project"

echo "GAMMA = 0.1"

SVM_MODEL_DIR=/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL/PERSON/RBF/svmModel_G_0.1.dat
TRAIN_DATABASE_DIR=/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL/PERSON/person_train.txt
CV_DATABASE_DIR=/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL/PERSON/person_val.txt
PREDS_DIR=/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL/PERSON/RBF/prcurve_G_0.1.pr
PREDS_DATABASE_DIR=/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL/PERSON/RBF/database_G_0.1.preds
SVM_CONFIG=/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL/PERSON/RBF/svm_G_0.1.config

echo "Starting the training ... "

./objdet TRAIN -c person -p $SVM_CONFIG $TRAIN_DATABASE_DIR $SVM_MODEL_DIR

echo "Staring the cross validation ..."

./objdet VAL -c person $CV_DATABASE_DIR $SVM_MODEL_DIR $PREDS_DIR $PREDS_DATABASE_DIR

echo "GAMMA = 0.0001"

SVM_MODEL_DIR=/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL/PERSON/RBF/svmModel_G_0.0001.dat
TRAIN_DATABASE_DIR=/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL/PERSON/person_train.txt
CV_DATABASE_DIR=/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL/PERSON/person_val.txt
PREDS_DIR=/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL/PERSON/RBF/prcurve_G_0.0001.pr
PREDS_DATABASE_DIR=/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL/PERSON/RBF/database_G_0.0001.preds
SVM_CONFIG=/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL/PERSON/RBF/svm_G_0.0001.config

echo "Starting the training ... "

./objdet TRAIN -c person -p $SVM_CONFIG $TRAIN_DATABASE_DIR $SVM_MODEL_DIR

echo "Staring the cross validation ..."

./objdet VAL -c person $CV_DATABASE_DIR $SVM_MODEL_DIR $PREDS_DIR $PREDS_DATABASE_DIR


echo "GAMMA = 10"

SVM_MODEL_DIR=/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL/PERSON/RBF/svmModel_G_10.dat
TRAIN_DATABASE_DIR=/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL/PERSON/person_train.txt
CV_DATABASE_DIR=/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL/PERSON/person_val.txt
PREDS_DIR=/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL/PERSON/RBF/prcurve_G_10.pr
PREDS_DATABASE_DIR=/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL/PERSON/RBF/database_G_10.preds
SVM_CONFIG=/Volumes/EXTERNAL/DISSERTATION/MODELS/PASCAL/PERSON/RBF/svm_G_10.config

echo "Starting the training ... "

./objdet TRAIN -c person -p $SVM_CONFIG $TRAIN_DATABASE_DIR $SVM_MODEL_DIR

echo "Staring the cross validation ..."

./objdet VAL -c person $CV_DATABASE_DIR $SVM_MODEL_DIR $PREDS_DIR $PREDS_DATABASE_DIR
